language: ruby
before_install:
  - "curl -sL https://s3.bixby.io/wad > ~/wad"
  - "chmod +x ~/wad"
install:
  - "travis_retry ~/wad"
before_script: "./bin/ci_setup.sh"
script: "./bin/ci.sh"
after_script:
  - "bundle exec rake coverage"
  - "bundle exec rake coveralls"

rvm:
  - 2.0.0-p598
  - 2.1.5
  - 2.2.0

branches:
  only:
    - master

env:
  global:
    - S3_REGION="us-east-1"
    - S3_BUCKET_NAME="io.bixby.gemcache.wad.agent"
    - secure: bnMJOHx5QrfTgOcxg0glw5x9mDoAJ0kKWILQaFCqwORwiJE4nh/3jYsx/uifVmSqOMXqY/9ozBwYrWeG6krPdcFCPS6mq4dVWsbtgQa31x9IWhjUg5lOt0MCrGXpq1JOD3CFIxnQ2f77hl0TzxutIfAtO023ad598+5/FVviyik=
