
install: bundle install --deployment
before_script: "./bin/ci_setup.sh"
script: "./bin/ci.sh"
after_script:
  - "bundle exec rake coverage"
  - "bundle exec rake coveralls"

language: ruby
cache: bundler
rvm:
  - 2.1.1
  - 1.9.3

branches:
  only:
    - master

env:
  global:
    - S3_REGION="us-east-1"
    - S3_BUCKET_NAME="io.bixby.gemcache.wad.agent"
    - secure: bnMJOHx5QrfTgOcxg0glw5x9mDoAJ0kKWILQaFCqwORwiJE4nh/3jYsx/uifVmSqOMXqY/9ozBwYrWeG6krPdcFCPS6mq4dVWsbtgQa31x9IWhjUg5lOt0MCrGXpq1JOD3CFIxnQ2f77hl0TzxutIfAtO023ad598+5/FVviyik=
